version: "3.8"

services:
  big-market:
    container_name: blog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - mysql
    networks:
      - mirror
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: big_market
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - mirror
networks:
  mirror: